[package]
name = "rust_nemu"
version = "0.1.0"
edition = "2021"




[features]
default = ["riscv32", "ftracer"]
riscv32 = []
riscv64 = []
ftracer = []

[dependencies]
colored = "2.1.0"
env_logger = "0.11.3"
goblin = "0.8.0"
log = "0.4.21"
